### ISSUE TITLE
to_local returns "aware" datetime

### ISSUE THREAD

**Issue by visionjosh** [nvie/times#10]
I think to_local should return a "naive" datetime object rather than an "aware" one. This would make the datetimes returned by the times module more consistent, as all the others are naive (which I think is a _great_ idea!).

I'm doing it locally by simply changing line 82 from 
return pytz.utc.localize(dt).astimezone(timezone)

to 

return pytz.utc.localize(dt).astimezone(timezone).replace(tzinfo=None)

Does this make sense to you? Thanks!

**Comment by nvie** [comment]
I'm closing old issues. If this issue still applies and requires my attention, I ask you kindly to re-open it or file a new issue. Thanks.
