### ISSUE TITLE
to_universal with only time string

### ISSUE THREAD

**Issue by visionjosh** [nvie/times#9]
Hi,

in to_universal, if you give it a string with just a time, such as "13:53:22" by default it fills in the date portion using datetime.datetime.now(). I think this is slightly wrong due to dates crossing the international date line. 

Instead, it should fill in the date portion using the date in the local timezone: to_local(datetime.datetime.utcnow(), timezone). 

I see that the string parsing is handled by the underlying dateutil module, so maybe this isn't the best place to bring it up?

**Comment by nvie** [comment]
I'd actually argue that this should be an error. `times` is a library mean for dealing with moments, not for time-of-day. That it even accepts this ambiguous string value I'd consider a bug.

**Comment by nvie** [comment]
I'm closing old issues. If this issue still applies and requires my attention, I ask you kindly to re-open it or file a new issue. Thanks.
